FROM postgres

RUN apt-get update -y
RUN apt-get dist-upgrade -y

RUN apt-get install ufw -y

RUN ufw allow from 172.18.1.2 to any port 5432
RUN ufw default reject incoming
RUN ufw enable
# ERROR: initcaps
# [Errno 2] iptables v1.6.0: can't initialize iptables table `filter': Permission denied (you must be root)
# Perhaps iptables or your kernel needs to be upgraded.
