#!/bin/bash

echo "Content-type: text/html";
echo ""

/bin/cat << EOM
<pre>
EOM

echo "<h1>IM SHOCKED!!!!</h1>"
date

env
echo "<h2>Users in $DB_ADDR</h2>"

/usr/bin/psql -h $DB_ADDR -d postgres -U postgres -c "select username, '********' as password from users;"


# TODO Enum users from postgres

/bin/cat << EOM
</pre>
EOM
