#!/bin/bash

echo "Content-type: text/html";
echo ""

/bin/cat << EOM
<pre>
EOM

echo "<h1>IM SHOCKED!!!!</h1>"
date

echo "<h2>Users</h2>"

psql -h $DB_ADDR -d shellshock -U shellshock -c "select username, '********' as password from users;"


# TODO Enum users from postgres

/bin/cat << EOM
</pre>
EOM
