services:
  frontend:
    build: ./front
    ports:
      - "2222:22"
      - "5000:5000"
      - "8080:8080"
    networks:
      - frontend
      - backend
  backend:
    build: back
    networks:
      - backend

networks:
  frontend:
  backend: