version: "3.3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    ports:
      - "127.0.0.1:8080:80"
    depends_on:
      - db
    links:
      - db
    networks:
      frontend:
        ipv4_address: 172.20.0.2
      backend:
        ipv4_address: 172.20.1.2
  db:
    image: postgres
    volumes:
      - ./pg_init/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      backend:
        ipv4_address: 172.20.1.3
networks:
  frontend:
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/24"
  backend:
    ipam:
      driver: default
      config:
        - subnet: "172.20.1.0/24"
