#!/bin/bash

echo "Content-type: text/html";
echo ""

/bin/cat << EOM
<pre>
EOM

echo "<h1>IM SHOCKED!!!!</h1>"
date

echo "<h2>Users in 172.18.1.3</h2>"
echo 'postgres' | /usr/bin/psql -h 172.18.1.3 -d postgres -U postgres --password -c "select username, '********' as password from usuarios;"


# TODO Enum users from postgres

/bin/cat << EOM
</pre>
EOM
